### PR TITLE
fix(auth): restrict /two-factor to 2FA

### LINKED ISSUE #16: Add TFA
Add TFA flow using better-auth.

### PR DESCRIPTION
**Pull request by ifeelBALANCED**
## Description

- Added two-factor authentication (TOTP): login flow with 2FA verify step, account settings to enable/disable 2FA, TOTP code input and QR setup in enable dialog.
- Web: new routes `two-factor` and two-factor-verify component; account two-factor-settings (enable/disable dialogs, hook); auth form and lib updates.
- API: removed invalid/unused trust-device-cookie import (module does not exist).

Closes #16

## Checklist

- [X] Changes are scoped and focused
- [X] Tested locally

### CODE REVIEW

File: apps/web/src/components/totp-code-input.tsx [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+const TOTP_LENGTH = 6
+
+interface TotpCodeInputProps {
+  id?: string
+  label?: string
+  value: string
+  onChange: (value: string) => void
+  onComplete?: VoidFunction
+  disabled?: boolean
```
Comment (Rudra-Sankha-Sinhamahapatra) [inline apps/web/src/components/totp-code-input.tsx]: hey the disable prop isn't being always used? so why you marked it as optional ?
