### PR TITLE
fix: boolean value updation to false from null

### LINKED ISSUE #292: Cannot update a nullable boolean column to false
### Bug description

`false` value is not saved

### Steps to reproduce

1. Creata a nullable boolean column
2. Set null value
3. Refresh the page
4. Double click on column
5. Click save
6. See the error

### Expected behavior

Value saved to false

### Conar version

0.26.0

### OS and environment

macOS

### Screenshots or logs

Image

Image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rudra-Sankha-Sinhamahapatra**
## Description of Changes

- What was changed?
If the value is boolean and not an array and if empty then it will be by default false
- Why was it changed?
because boolean value updation from null was not working
- Any related issues or discussions?

Closes #292 (If applicable, delete this line if not)

## Checklist

- [x] My changes are scoped and focused
- [x] I have tested the code locally

## Notes to reviewer

- Are there any specific things the reviewer should focus on?

### CODE REVIEW

File: apps/desktop/src/entities/database/utils/render.ts [hunk 1]
```diff
@@ -1,11 +1,13 @@
...
+
 function prepareValue(value: unknown) {
   if (value instanceof Date)
     return value.toISOString()
 
   return value
 }
 
-export function getEditableValue(value: unknown, oneLine: boolean) {
+export function getEditableValue(value: unknown, oneLine: boolean, column?: Column) {
```
Comment (letstri) [inline apps/desktop/src/entities/database/utils/render.ts]: make column not optional and convert params to obj

File: apps/desktop/src/entities/database/utils/render.ts [hunk 2]
```diff
@@ -14,12 +16,15 @@ export function getEditableValue(value: unknown, oneLine: boolean) {
...
+  if (column && column.type === 'boolean' && !column.isArray && _value === null)
+    return 'false'
+
   return oneLine
     ? String(_value ?? '').replaceAll('\n', ' ')
     : String(_value ?? '')
 }
 
-export function getDisplayValue(value: unknown, size: number) {
+export function getDisplayValue(value: unknown, size: number, column?: Column) {
```
Comment (letstri) [inline apps/desktop/src/entities/database/utils/render.ts]: same

Comment (Rudra-Sankha-Sinhamahapatra) [reply apps/desktop/src/entities/database/utils/render.ts]: done

File: apps/desktop/src/entities/database/utils/render.ts (hunk 1 above)
Comment (Rudra-Sankha-Sinhamahapatra) [reply apps/desktop/src/entities/database/utils/render.ts]: done
