### PR TITLE
fix: dark mode issue on web

### LINKED ISSUE #270: Website shows light mode on loading
The website https://conar.app shows dark mode during first two seconds then turning it into light

### PR DESCRIPTION
**Pull request by Rudra-Sankha-Sinhamahapatra**
## Description of Changes

- What was changed?
1. Modified 
```packages/ui/src/components/sonner.tsx```
 to delay Toaster rendering until after component mount using useEffect

- Why was it changed?
1. Fixed ~2 second flash of light mode on initial page load

2. The Toaster component (using createPortal) was rendering before 
ThemeObserver could apply the dark class to the <html> element, causing the flash

3. Fixed Rules of Hooks violation by ensuring React hooks are called before conditional returns

- Any related issues or discussions?

Closes #270  (If applicable, delete this line if not)

## Checklist

- [x] My changes are scoped and focused
- [x] I have tested the code locally

## Notes to reviewer

https://github.com/user-attachments/assets/2c021076-8abe-4f47-81db-12ecb33b0684

- Are there any specific things the reviewer should focus on?

cc: @letstri @geekyharsh05

### CODE REVIEW

File: packages/ui/src/components/sonner.tsx [hunk 1]
```diff
@@ -1,12 +1,19 @@
+import { useEffect, useState } from 'react'
 import { createPortal } from 'react-dom'
 import { Toaster as Sonner } from 'sonner'
 import { useTheme } from '../theme-observer'
 
 function Toaster() {
   const { resolvedTheme } = useTheme()
+  const [isMounted, setIsMounted] = useState(false)
```
Comment (letstri) [inline packages/ui/src/components/sonner.tsx]: use our hook from hookas

Comment (Rudra-Sankha-Sinhamahapatra) [reply packages/ui/src/components/sonner.tsx]: done
