### PR TITLE
fix: fix jsonb save

### LINKED ISSUE #95: JSONB save error
### Bug description

When saving a jsonb cell, an error is thrown "Invalid input syntax for type json"

### Steps to reproduce

1. Connect to a Postgres DB with a jsonb cell type
2. Try to edit the cell and save

### Expected behavior

Sucess on save

### Conar version

v0.14.0

### OS and environment

macOS

### Screenshots or logs

Image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nleborgne**
## Description of Changes

- What was changed?
Changed the `isJson` const

- Why was it changed?
In case of jsonb types, it would parse the value and return a JSON instead of a string

- Any related issues or discussions?
Closes #95

## Checklist

- [x] My changes are scoped and focused
- [x] I have tested the code locally

## Notes to reviewer

- Are there any specific things the reviewer should focus on?

### CODE REVIEW

**Comment by letstri** [comment]
Hello, thank you for your pull request! I tested your solution and it works for jsonb columns, but it still doesn't work for json.

I suggest doing it differently: removing the json check altogether and adding only the json language to monaco.

I can do it for you if you don't have time.

**Comment by nleborgne** [comment]
Thank you for your response, I remove the `isJson` check and changed the language condition inside monaco editor to include json and jsonb.

It seems to work well for both data types, I'll let you try it to check if it's implemented correctly.

File: apps/desktop/src/entities/database/components/table-cell.tsx [hunk 1]
```diff
@@ -146,7 +140,7 @@ function TableCellMonaco({
       <Monaco
         data-mask
         value={value}
-        language={isJson ? 'json' : undefined}
```
Comment (letstri) [inline apps/desktop/src/entities/database/components/table-cell.tsx:149]: why not `column?.type.includes('json')`?

File: apps/desktop/src/entities/database/components/table-cell.tsx [hunk 2]
```diff
@@ -146,7 +140,7 @@ function TableCellMonaco({
...
+        language={['json', 'jsonb'].includes(column?.type ?? '') ? 'json' : undefined}
```
Comment (letstri) [inline apps/desktop/src/entities/database/components/table-cell.tsx:143]: why not `column?.type.includes('json')`?

**Comment by letstri** [comment]
This is exactly what I wanted, thank you very much!
